#!/bin/bash

/usr/bin/trayer --edge top --align right --widthtype request --expand true --SetDockType true --SetPartialStrut true --transparent true --alpha 0 --tint 0x1A1918 --expand true --heighttype pixel --height 14 --monitor 1 --padding 1 &

if [ -x /usr/bin/nm-applet ] ; then
   (sleep 1; nm-applet &)
fi

/usr/bin/redshift-gtk >/home/tanya/poop  2>&1 &

/usr/bin/autocutsel -fork & /usr/bin/autocutsel -selection PRIMARY -fork &

/usr/bin/gnome-sound-applet &

exec xmonad
