#!/bin/bash

/usr/bin/trayer --edge top --align right --widthtype request --expand true --SetDockType true --SetPartialStrut true --transparent true --alpha 0 --tint 0x1A1918 --expand true --heighttype pixel --height 14 --monitor 1 --padding 1 &

if [ -x /usr/bin/nm-applet ] ; then
   (sleep 1; nm-applet &)
fi

/home/tanya/battery-alert.sh &

/usr/bin/redshift-gtk &

/usr/bin/autocutsel -fork & /usr/bin/autocutsel -selection PRIMARY -fork &

/usr/bin/gnome-sound-applet &

/usr/bin/feh --randomize --bg-max /home/tanya/Pictures/background/ &

exec xmonad
